import { 
    product1Img,product2Img,product3Img,product4Img,product5Img,product6Img,product7Img,product8Img,product9Img,product10Img,product11Img,product12Img,product13Img,product14Img,product15Img,
    suggest1,suggest9,
    img15,img16,img17,img18,
} from "./img.js"

const products = [
    {
        id: 1,
        isSale: true,
        img: product1Img,
        name: 'Modular Modern',
        oldPrice: 9.00,
        newPrice: 7.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 2,
        isSale: false,
        img: product2Img,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 10.00,
        rating: 3.5,
        categorys: ['Coffee Tables'],
    },
    {
        id: 3,
        isSale: true,
        img: product3Img,
        name: 'Modular Modern',
        oldPrice: 3.00,
        newPrice: 2.00,
        rating: 2,
        categorys: ['Coffee Tables'],
    },
    {
        id: 4,
        isSale: false,
        img: product4Img,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 13.00,
        rating: 3,
        categorys: ['Coffee Tables'],
    },
    {
        id: 5,
        isSale: false,
        img: product5Img,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 14.00,
        rating: 3,
        categorys: ['Coffee Tables'],
    },
    {
        id: 6,
        isSale: false,
        img: product6Img,
        name: 'Praesent at',
        oldPrice: '',
        newPrice: 15.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 7,
        isSale: false,
        img: product7Img,
        name: 'Laoreet ultrices',
        oldPrice: '',
        newPrice: 35.00,
        rating: 4,
        categorys: ['Sofas'],
    },
    {
        id: 8,
        isSale: true,
        img: product8Img,
        name: 'Nisi vitae',
        oldPrice: 40,
        newPrice: 35.00,
        rating: 4,
        categorys: ['Sofas'],
    },
    {
        id: 9,
        isSale: false,
        img: product9Img,
        name: 'Maecenas consequat',
        oldPrice: '',
        newPrice: 35.00,
        rating: 4,
        categorys: ['Sofas'],
    },
    {
        id: 10,
        isSale: false,
        img: product10Img,
        name: 'Patient sofa',
        oldPrice: '',
        newPrice: 30.00,
        rating: 3,
        categorys: ['Sofas'],
    },
    {
        id: 11,
        isSale: true,
        img: product11Img,
        name: 'Iaculis orci',
        oldPrice: 40.00,
        newPrice: 35.00,
        rating: 4.5,
        categorys: ['Sofas'],
    },
    {
        id: 12,
        isSale: true,
        img: product12Img,
        name: 'Variable Product – Color',
        oldPrice: 48.00,
        newPrice: 45.00,
        rating: 4,
        categorys: ['Sofas'],
    },
    {
        id: 13,
        isSale: true,
        img: product13Img,
        name: 'Variable Product – Image',
        oldPrice: 35.00,
        newPrice: 32.00,
        rating: 4,
        categorys: ['Sofas'],
    },
    {
        id: 14,
        isSale: true,
        img: product14Img,
        name: 'Curabitur non',
        oldPrice: 60,
        newPrice: 54.00,
        rating: 3,
        categorys: ['Sofas'],
    },
    {
        id: 15,
        isSale: false,
        img: product15Img,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 15.00,
        rating: 3,
        categorys: ['Coffee Tables'],
    },
    {
        id: 16,
        isSale: true,
        img: product3Img,
        name: 'Modular Modern',
        oldPrice: 9.00,
        newPrice: 7.00,
        rating: 3.5,
        categorys: ['Coffee Tables'],
    },
    {
        id: 17,
        isSale: true,
        img: product2Img,
        name: 'External/Affiliate Product',
        oldPrice: 9.00,
        newPrice: 8.00,
        rating: 5,
        categorys: ['Coffee Tables'],
    },
    {
        id: 18,
        isSale: false,
        img: product4Img,
        name: 'Variable Product',
        oldPrice: '',
        newPrice: 9.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 19,
        isSale: false,
        img: product5Img,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 9.00,
        rating: 3,
        categorys: ['Coffee Tables'],
    },
    {
        id: 20,
        isSale: false,
        img: img15,
        name: 'Variable Product',
        oldPrice: '',
        newPrice: 9.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 21,
        isSale: false,
        img: suggest1,
        name: 'Modular Modern',
        oldPrice: '',
        newPrice: 9.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 22,
        isSale: false,
        img: img16,
        name: 'Donec Cursus',
        oldPrice: '',
        newPrice: 15.00,
        rating: 0,
        categorys: ['Coffee Tables'],
    },
    {
        id: 23,
        isSale: true,
        img: img17,
        name: 'Grouped Product',
        oldPrice: 9.00,
        newPrice: 15.00,
        rating: 4,
        categorys: ['Coffee Tables'],
    },
    {
        id: 24,
        isSale: true,
        img: suggest9,
        name: 'scelerisque accumsan',
        oldPrice: 15.00,
        newPrice: 12.00,
        rating: 2,
        categorys: ['Coffee Tables'],
    },
    {
        id: 25,
        isSale: true,
        img: img18,
        name: 'Urna in eros',
        oldPrice: 15.00,
        newPrice: 12.00,
        rating: 4,
        categorys: ['Coffee Tables'],
    },
]

export default products